version: "3.8"

networks:
  panel:

volumes:
  database:
    driver: local
    driver_opts:
      type: none
      device: /var/panelData/mariadb
      o: bind
  redis:
    driver: local
    driver_opts:
      type: none
      device: /var/panelData/redis
      o: bind

services:
  database:
    image: mariadb:11.2.2-jammy
    container_name: ${PROJECT_NAME}_database
    restart: always
    stdin_open: true
    tty: true
    environment:
      MARIADB_DATABASE: ${DB_DATABASE}
      MARIADB_USER: ${DB_USERNAME}
      MARIADB_PASSWORD: ${DB_PASSWORD}
      MARIADB_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - "database:/var/lib/mysql"
      - "./docker/database/init:/docker-entrypoint-initdb.d"
    networks:
      - panel
    ports:
      - "${DB_PORT}:3306"

  redis:
    image: redis:7.2.3-alpine3.19
    container_name: ${PROJECT_NAME}_redis
    restart: always
    stdin_open: true
    tty: true
    command: redis-server --save 20 1 --loglevel warning --requirepass ${REDIS_PASSWORD}
    networks:
      - panel
    volumes:
      - "redis:/data"
