version: "3.8"

networks:
  panel:
  traefik_net:
    external: true

services:
  nginx:
    image: ${IMAGE_PREFIX}_nginx
    volumes:
      - "/home/arsolitt/projects/Protesian/panel:/var/www/panel"
      - "/home/arsolitt/projects/Protesian/docker/nginx/nginx.conf:/etc/nginx/nginx.conf"
      - "/home/arsolitt/projects/Protesian/docker/nginx/configs/default.conf:/etc/nginx/conf.d/default.conf"
    networks:
      - panel
      - traefik_net
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.protesian.entrypoints=https"
        - "traefik.http.routers.protesian.tls.certresolver=letsencrypt"
        - "traefik.http.routers.protesian.rule=Host(`protesian.arsolitt.online`)"
        - "traefik.http.services.protesian.loadbalancer.server.port=80"

  database:
    image: mariadb:11.2.2-jammy
    stdin_open: true
    tty: true
    environment:
      MARIADB_DATABASE: ${DB_DATABASE}
      MARIADB_USER: ${DB_USERNAME}
      MARIADB_PASSWORD: ${DB_PASSWORD}
      MARIADB_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - "/home/arsolitt/projects/Protesian/docker/database/data:/var/lib/mysql"
      - "/home/arsolitt/projects/Protesian/docker/database/init:/docker-entrypoint-initdb.d"
    networks:
      - panel
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]

  redis:
    image: redis:7.2.3-alpine3.19
    stdin_open: true
    tty: true
    command: redis-server --save 20 1 --loglevel warning --requirepass ${REDIS_PASSWORD}
    networks:
      - panel
    volumes:
      - "/home/arsolitt/projects/Protesian/docker/redis/data:/data"
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]

  app:
    stdin_open: true
    tty: true
    image: ${IMAGE_PREFIX}_php
    depends_on:
      - redis
      - database
      - nginx
    volumes:
      - "/home/arsolitt/projects/Protesian/panel:/var/www/panel"
    networks:
      - panel
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]

  scheduler:
    stdin_open: true
    tty: true
    image: ${IMAGE_PREFIX}_php
    entrypoint: ["/home/tools/role.sh"]
    depends_on:
      - redis
      - database
      - app
    environment:
      CONTAINER_ROLE: scheduler
    volumes:
      - "/home/arsolitt/projects/Protesian/panel:/home/app"
    networks:
      - panel
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]

  queue:
    stdin_open: true
    tty: true
    image: ${IMAGE_PREFIX}_php
    entrypoint: ["/home/tools/role.sh"]
    depends_on:
      - redis
      - database
      - app
    environment:
      CONTAINER_ROLE: queue
    volumes:
      - "/home/arsolitt/projects/Protesian/panel:/home/app"
    networks:
      - panel
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]

  composer:
    stdin_open: true
    tty: true
    image: ${IMAGE_PREFIX}_php
    entrypoint: ["/usr/bin/composer"]
    volumes:
      - "/home/arsolitt/projects/Protesian/panel:/home/app"
    networks:
      - panel
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]

  artisan:
    stdin_open: true
    tty: true
    image: ${IMAGE_PREFIX}_php
    entrypoint: ["php", "/home/app/artisan"]
    volumes:
      - "/home/arsolitt/projects/Protesian/panel:/home/app"
    networks:
      - panel
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]

  yarn:
    image: ${IMAGE_PREFIX}_node
    stdin_open: true
    tty: true
    volumes:
      - "/home/arsolitt/projects/Protesian/panel:/home/app"
    networks:
      - panel
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]
