apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-php
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  APP_ENV: production
  APP_DEBUG: "false"
  APP_KEY: {{ .Values.secrets.php.appKey }}
  APP_THEME: jexactyl
  APP_TIMEZONE: Europe/Moscow
  APP_URL: https://{{ .Values.domain.name }}
  APP_LOCALE: ru
  APP_ENVIRONMENT_ONLY: "true"

  RECAPTCHA_ENABLED: "true"
  RECAPTCHA_WEBSITE_KEY: {{ .Values.secrets.php.recaptcha.key }}
  RECAPTCHA_SECRET_KEY: {{ .Values.secrets.php.recaptcha.secret }}

  LOG_CHANNEL: daily
  LOG_DEPRECATIONS_CHANNEL: "null"
  LOG_LEVEL: debug

  DB_CONNECTION: {{ .Values.secrets.php.db.connection }}
  DB_HOST: {{ .Values.secrets.php.db.host }}
  DB_PORT: "{{ .Values.secrets.php.db.port }}"
  DB_DATABASE: {{ .Values.secrets.php.db.database }}
  DB_USERNAME: {{ .Values.secrets.php.db.username }}
  DB_PASSWORD: {{ .Values.secrets.php.db.password }}

  REDIS_HOST: {{ .Values.secrets.php.redis.host }}
  REDIS_PORT: "{{ .Values.secrets.php.redis.port }}"
  REDIS_PASSWORD: {{ .Values.secrets.php.redis.password }}

  CACHE_DRIVER: redis
  QUEUE_CONNECTION: redis
  SESSION_DRIVER: redis

  HASHIDS_SALT: {{ .Values.secrets.php.hash.salt }}
  HASHIDS_LENGTH: "{{ .Values.secrets.php.hash.len }}"

  MAIL_MAILER: {{ .Values.secrets.php.mail.mailer }}
  MAIL_HOST: {{ .Values.secrets.php.mail.host }}
  MAIL_PORT: "{{ .Values.secrets.php.mail.port }}"
  MAIL_ENCRYPTION: tls
  MAIL_USERNAME: {{ .Values.secrets.php.mail.username }}
  MAIL_PASSWORD: {{ .Values.secrets.php.mail.password }}
  MAIL_FROM_ADDRESS: {{ .Values.secrets.php.mail.fromAddress }}
  MAIL_FROM_NAME: {{ .Values.secrets.php.mail.fromName }}

  YOOKASSA_SHOP_ID: "{{ .Values.secrets.php.payment.yookassa.shopId }}"
  YOOKASSA_SECRET_KEY: {{ .Values.secrets.php.payment.yookassa.secretKey }}

