#version: "3.8"

networks:
  panel:

volumes:
  database:
    driver: local
  redis:
    driver: local

services:
  nginx:
    build:
      context: .
      dockerfile: nginx.Dockerfile
      args:
        UID: ${UID}
        GID: ${GID}
    image: ${PROJECT_NAME}_nginx
    container_name: ${PROJECT_NAME}_nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - "../panel:/var/www/panel"
      - "./nginx.conf:/etc/nginx/nginx.conf"
    networks:
      - panel

  database:
    image: mariadb:11.2.2-jammy
    container_name: ${PROJECT_NAME}_database
    restart: unless-stopped
    stdin_open: true
    tty: true
    environment:
      MARIADB_DATABASE: ${DB_DATABASE}
      MARIADB_USER: ${DB_USERNAME}
      MARIADB_PASSWORD: ${DB_PASSWORD}
      MARIADB_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - "database:/var/lib/mysql"
    networks:
      - panel
    ports:
      - "3306:3306"

  redis:
    image: redis:7.2.3-alpine3.19
    container_name: ${PROJECT_NAME}_redis
    restart: unless-stopped
    stdin_open: true
    tty: true
    command: redis-server --save 20 1 --loglevel warning --requirepass ${REDIS_PASSWORD}
    networks:
      - panel
    volumes:
      - "redis:/data"

  app:
    build:
      context: .
      dockerfile: php.Dockerfile
      args:
        UID: ${UID}
        GID: ${GID}
    stdin_open: true
    tty: true
    image: ${PROJECT_NAME}_php
    container_name: ${PROJECT_NAME}_app
    depends_on:
      - redis
      - database
      - nginx
    volumes:
      - "../panel:/var/www/panel"
    networks:
      - panel

  scheduler:
    build:
      context: .
      dockerfile: php.Dockerfile
      args:
        UID: ${UID}
        GID: ${GID}
    stdin_open: true
    tty: true
    restart: unless-stopped
    image: ${PROJECT_NAME}_php
    container_name: ${PROJECT_NAME}_scheduler
    entrypoint: ["php", "/home/app/artisan", "schedule:work",  "--verbose", "--no-interaction"]
    depends_on:
      - redis
      - database
      - app
    volumes:
      - "../panel:/home/app"
    networks:
      - panel

  queue:
    build:
      context: .
      dockerfile: php.Dockerfile
      args:
        UID: ${UID}
        GID: ${GID}
    stdin_open: true
    tty: true
    restart: unless-stopped
    image: ${PROJECT_NAME}_php
    container_name: ${PROJECT_NAME}_queue
    entrypoint: ["php", "/home/app/artisan", "queue:work", "--verbose", "--tries=3"]
    depends_on:
      - redis
      - database
      - app
    volumes:
      - "../panel:/home/app"
    networks:
      - panel

  composer:
    build:
      context: .
      dockerfile: php.Dockerfile
      args:
        UID: ${UID}
        GID: ${GID}
    stdin_open: true
    tty: true
    image: ${PROJECT_NAME}_php
    entrypoint: ["/usr/bin/composer"]
    volumes:
      - "../panel:/home/app"
    networks:
      - panel

  artisan:
    build:
      context: .
      dockerfile: php.Dockerfile
      args:
        UID: ${UID}
        GID: ${GID}
    stdin_open: true
    tty: true
    image: ${PROJECT_NAME}_php
    entrypoint: ["php", "/home/app/artisan"]
    volumes:
      - "../panel:/home/app"
    networks:
      - panel

  yarn:
    build:
      context: .
      dockerfile: node.Dockerfile
      args:
        UID: ${UID}
        GID: ${GID}
    image: ${PROJECT_NAME}_node
    stdin_open: true
    tty: true
    volumes:
      - "../panel:/home/app"
    networks:
      - panel
