name: Deploy to Development
on:
  push:
    branches:
      - development
  pull_request:
    branches:
      - development
  workflow_dispatch:

jobs:
  # build-php:
  #   name: Build PHP
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4
  #     - name: Short SHA
  #       id: short-sha
  #       uses: benjlevesque/short-sha@v3.0
  #       with:
  #         length: 7
  #     - name: Build and push php
  #       uses: aevea/action-kaniko@master
  #       with:
  #         image: arsolitt/jexactyl-php
  #         build_file: php.Dockerfile
  #         username: ${{ secrets.DOCKERHUB_USERNAME }}
  #         password: ${{ secrets.DOCKERHUB_PASSWORD }}
  #         tag: ${{ steps.short-sha.outputs.sha }}
  #         tag_with_latest: true
  #         cache: true
  #         cache_registry: arsolitt/jexactyl-cache
  # build-nginx:
  #   name: Build NGINX
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4
  #     - name: Short SHA
  #       id: short-sha
  #       uses: benjlevesque/short-sha@v3.0
  #       with:
  #         length: 7
  #     - name: Build and push nginx
  #       uses: aevea/action-kaniko@master
  #       with:
  #         image: arsolitt/jexactyl-nginx
  #         build_file: nginx.Dockerfile
  #         username: ${{ secrets.DOCKERHUB_USERNAME }}
  #         password: ${{ secrets.DOCKERHUB_PASSWORD }}
  #         tag: ${{ steps.short-sha.outputs.sha }}
  #         tag_with_latest: true
  #         cache: true
  #         cache_registry: arsolitt/jexactyl-cache
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: Development
    # needs: [build-php, build-nginx]
    steps:
      - uses: actions/checkout@v4

      - name: Short SHA
        id: short-sha
        uses: benjlevesque/short-sha@v3.0
        with:
          length: 7

      - name: Install Helm
        uses: azure/setup-helm@v3

      - name: Decode Kubeconfig
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
          DB_HOST: ${{ secrets.DB_HOST }}
        run: |
          echo $DB_HOST > $HOME/dbhost.txt && cat $HOME/dbhost.txt

      - name: Test Kubeconfig
        run: |
          kubectl --kubeconfig=kubeconfig cluster-info

      - name: Deploy with Helm
        # env:
        #   KUBECONFIG: ./kubeconfig
        run: |
          helm upgrade --install jexactyl -n protesian-dev --create-namespace .kubernetes/ \
          --set images.php=arsolitt/jexactyl-php:latest
          --set images.nginx='arsolitt/jexactyl-nginx:latest
          --set secrets.php.appKey=${{ secrets.APP_KEY }} \
          --set secrets.php.recaptcha.key=${{ secrets.RECAPTCHA_WEBSITE_KEY }} \
          --set secrets.php.recaptcha.secret=${{ secrets.RECAPTCHA_SECRET_KEY }} \
          --set secrets.php.db.host=${{ secrets.DB_HOST }} \
          --set secrets.php.db.database=${{ secrets.DB_DATABASE }} \
          --set secrets.php.db.username=${{ secrets.DB_USERNAME }} \
          --set secrets.php.db.password=${{ secrets.DB_PASSWORD }} \
          --set secrets.php.redis.host=${{ secrets.REDIS_HOST }} \
          --set secrets.php.redis.password=${{ secrets.REDIS_PASSWORD }} \
          --set secrets.php.hash.salt=${{ secrets.HASHIDS_SALT }} \
          --set secrets.php.hash.len=${{ secrets.HASHIDS_LENGTH }} \
          --set secrets.php.mail.username=${{ secrets.MAIL_USERNAME }} \
          --set secrets.php.mail.password=${{ secrets.MAIL_PASSWORD }} \
          --set secrets.php.payment.yookassa.shopId=${{ secrets.YOOKASSA_SHOP_ID }} \
          --set secrets.php.payment.yookassa.secretKey=${{ secrets.YOOKASSA_SECRET_KEY }} \
          --set-string whitelist.sources="{vars.WHITELIST}" \
          --kubeconfig=kubeconfig
  # deploy:
  #   name: Deploy
  #   runs-on: ubuntu-latest
  #   environment: Development
  #   needs: [build-php, build-nginx]
  #   steps:
  #     - uses: actions/checkout@v4

  #     - name: Short SHA
  #       id: short-sha
  #       uses: benjlevesque/short-sha@v3.0
  #       with:
  #         length: 7

  #     - name: Install Helm
  #       uses: azure/setup-helm@v3

  #     - name: Decode Kubeconfig
  #       env:
  #         KUBE_CONFIG_DATA: ${{ secrets.KUBECONFIG }}
  #       run: |
  #         echo "${KUBE_CONFIG_DATA}" | base64 -d > kubeconfig

  #     - name: Deploy with Helm
  #       env:
  #         KUBECONFIG: ./kubeconfig
  #       run: |
  #         helm upgrade --install jexactyl -n protesian-dev --create-namespace .kubernetes/ \
  #         --set images.php=arsolitt/jexactyl-php:${{ steps.short-sha.outputs.sha }}
  #         --set images.nginx='arsolitt/jexactyl-nginx:${{ steps.short-sha.outputs.sha }}
  #         --set secrets.php.appKey=${{ secrets.APP_KEY }} \
  #         --set secrets.php.recaptcha.key=${{ secrets.RECAPTCHA_WEBSITE_KEY }} \
  #         --set secrets.php.recaptcha.secret=${{ secrets.RECAPTCHA_SECRET_KEY }} \
  #         --set secrets.php.db.host=${{ secrets.DB_HOST }} \
  #         --set secrets.php.db.database=${{ secrets.DB_DATABASE }} \
  #         --set secrets.php.db.username=${{ secrets.DB_USERNAME }} \
  #         --set secrets.php.db.password=${{ secrets.DB_PASSWORD }} \
  #         --set secrets.php.redis.host=${{ secrets.REDIS_HOST }} \
  #         --set secrets.php.redis.password=${{ secrets.REDIS_PASSWORD }} \
  #         --set secrets.php.hash.salt=${{ secrets.HASHIDS_SALT }} \
  #         --set secrets.php.hash.len=${{ secrets.HASHIDS_LENGTH }} \
  #         --set secrets.php.mail.username=${{ secrets.MAIL_USERNAME }} \
  #         --set secrets.php.mail.password=${{ secrets.MAIL_PASSWORD }} \
  #         --set secrets.php.payment.yookassa.shopId=${{ secrets.YOOKASSA_SHOP_ID }} \
  #         --set secrets.php.payment.yookassa.secretKey=${{ secrets.YOOKASSA_SECRET_KEY }} \
  #         --set-string whitelist.sources="{vars.WHITELIST}"
