name: Deploy to Development
on:
  push:
    branches:
      - development
  pull_request:
    branches:
      - development
  workflow_dispatch:

jobs:
  build-php:
    name: Build and push artifacts to registry
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Short SHA
        id: short-sha
        uses: benjlevesque/short-sha@v3.0
        with:
          length: 7
      - name: Build and push php
        uses: aevea/action-kaniko@master
        with:
          image: arsolitt/jexactyl-php
          build_file: .kubernetes/php.Dockerfile
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          tag: ${{ steps.short-sha.outputs.sha }}
          tag_with_latest: true
          cache: true
          cache_registry: arsolitt/cache-jexactyl-php
  build-nginx:
    name: Build and push artifacts to registry
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Short SHA
        id: short-sha
        uses: benjlevesque/short-sha@v3.0
        with:
          length: 7
      - name: Build and push nginx
        uses: aevea/action-kaniko@master
        with:
          image: arsolitt/jexactyl-nginx
          build_file: .kubernetes/nginx.Dockerfile
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          tag: ${{ steps.short-sha.outputs.sha }}
          tag_with_latest: true
          cache: true
          cache_registry: arsolitt/cache-jexactyl-nginx
  deploy:
    needs: [build-php, build-nginx]
    name: Deploy to Kubernetes
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Deploy
        uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
        with:
          args: "apply -f .kubernetes -n protesian-dev"
      - uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
        with:
          args: "apply -f .kubernetes -n protesian-dev"
