name: Deploy to Production
on:
  pull_request:
    branches:
      - main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get source commit SHA
        id: get_source_commit
        run: |
          DEV_COMMIT=$(git rev-parse origin/${{ github.event.pull_request.head.ref }})
          DEV_COMMIT_SHORT=${DEV_COMMIT::7}
          echo "::set-output name=source_commit::$DEV_COMMIT_SHORT"

      - name: Install Helm
        uses: azure/setup-helm@v3

      - uses: akiojin/decode-base64-github-action@v0.1.0
        with:
          base64: ${{ secrets.KUBE_CONFIG }}
          output-path: ${{ runner.temp }}/kubeconfig

      - name: Deploy with Helm
        run: >
          helm upgrade --install jexactyl-prod -n protesian --create-namespace --kubeconfig=${{ runner.temp }}/kubeconfig .kubernetes/
          --set images.php=arsolitt/jexactyl-php:${{ steps.get_source_commit.outputs.source_commit }}
          --set images.nginx=arsolitt/jexactyl-nginx:${{ steps.get_source_commit.outputs.source_commit }}
          --set domain.name=${{ vars.DOMAIN_NAME }}
          --set domain.secret=${{ vars.DOMAIN_SECRET }}
          --set secrets.php.appName=${{ secrets.APP_NAME }}
          --set secrets.php.appKey=${{ secrets.APP_KEY }}
          --set secrets.php.recaptcha.key=${{ secrets.RECAPTCHA_WEBSITE_KEY }}
          --set secrets.php.recaptcha.secret=${{ secrets.RECAPTCHA_SECRET_KEY }}
          --set secrets.php.db.host=${{ vars.DB_HOST }}
          --set secrets.php.db.database=${{ secrets.DB_DATABASE }}
          --set secrets.php.db.username=${{ secrets.DB_USERNAME }}
          --set secrets.php.db.password=${{ secrets.DB_PASSWORD }}
          --set secrets.php.redis.host=${{ vars.REDIS_HOST }}
          --set secrets.php.redis.password=${{ secrets.REDIS_PASSWORD }}
          --set secrets.php.hash.salt=${{ secrets.HASHIDS_SALT }}
          --set secrets.php.hash.len=${{ secrets.HASHIDS_LENGTH }}
          --set secrets.php.mail.fromAddress=${{ vars.MAIL_FROM_ADDRESS }}
          --set secrets.php.mail.fromName="${{ vars.MAIL_FROM_NAME }}"
          --set secrets.php.mail.username=${{ secrets.MAIL_USERNAME }}
          --set secrets.php.mail.password=${{ secrets.MAIL_PASSWORD }}
          --set secrets.php.payment.yookassa.shopId=${{ secrets.YOOKASSA_SHOP_ID }}
          --set secrets.php.payment.yookassa.secretKey=${{ secrets.YOOKASSA_SECRET_KEY }}
          --set-string replicas.app=2
          --set-string whitelist.enabled=""
          --set-string whitelist.sources="{${{ vars.WHITELIST }}}"
